# Tên ứng dụng
spring.application.name=student

# Cấu hình H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# QUAN TRỌNG: Tự động cập nhật cấu trúc bảng khi chạy lại
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Hiện câu lệnh SQL trong terminal để dễ debug
spring.jpa.show-sql=true

# Cấu hình Swagger (nếu cần thiết)
springdoc.packages-to-scan=com.example.student.controller